# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54e6afe7552a821176bbfec9968e0cef5147c0a6576effaef0460c1131396d4d9cd6b8b3df4d076b678c1bc7feb2c20dc96d6ad334863580845a926985dc5ea2

test:
  secret_key_base: af74fba27980d97562a35e8a93392806384ef0daeb49b7e8cecf7db9140866ea25bff9c187ddfc9f1e263f84b135a656023ec9da54ce0fca5bae63f1803d2fb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
